module.exports  = [{
                            rating: 'R',
                            percent: 47.1,
                            class: "progress-bar-success"
                        }, {
                            rating: 'PG-13',
                            percent: 30.8,
                            class: "progress-bar-info"
                        }, {
                            rating: 'PG',
                            percent: 11.2,
                            class: "progress-bar-warning"
                        }, {
                            rating: 'G',
                            percent: 1.8
                        }, {
                            rating: 'NC-17',
                            percent: 0.2
                        }].slice(0, 3)